version: '3'


services:

# Spark containers
  master:
    image: spark-master:2.3.3

    networks:
      default:
        aliases:
          - spark_master
    
    ports:
#      - "7077:7077"  # Spark master port
#      - "6066:6066"  # spark rest api
      - "8080:8080"  # Spark master web UI

    volumes:
      - "${DATA_DIR:-/tmp}:/spark/data"

    user: root

    # command to start spark server
    command: /spark/start-spark-master.sh

  worker1:
    image: spark-worker:2.3.3

    networks:
      default:
        aliases:
          - spark_worker1

    ports:
      - "8081:8081"

    volumes:
      - "${DATA_DIR:-/tmp}:/spark/data"

    user: root

    # command to start spark server
    command: /spark/start-spark-worker.sh  --cores 4 --memory 4g  --port 8081

  worker2:
    image: spark-worker:2.3.3

    networks:
      default:
        aliases:
          - spark_worker2

    ports:
      - "8082:8082"

    volumes:
      - "${DATA_DIR:-/tmp}:/spark/data"

    user: root

    # command to start spark server
    command: /spark/start-spark-worker.sh  --cores 4 --memory 4g --port 8082

  pyspnb:
    image: spark-pyspnb:2.3.3

    networks:
      default:
        aliases:
          - spark_client

    ports:
      - "8888:8888"  # jupyter notebook server
      - "4040:4040"  # spark job web ui

    volumes:
      - "${CODE_DIR:-/tmp}:/opt/project"
      - "${DATA_DIR:-/tmp}:/spark/data"

    user: root

    # command jupyter notebook server
    command: /spark/start-pyspnb.sh

#
#    tty: true
#    stdin_open: true