version: '3'


services:

# Spark containers
  master:
    image: spark-master:2.3.3
    
    ports:
      - "7077:7077"  # Spark master port
      - "6066:6066"  # spark rest api
      - "8080:8080"  # Spark master web UI

    volumes:
      - "${PWD}/data:/spark/data"

    user: root

    # command to start spark server
    command: /spark/start-spark-master.sh

  worker1:
    image: spark-worker:2.3.3

    volumes:
      - "${PWD}/data:/spark/data"

    user: root

    # command to start spark server
    command: /spark/start-spark-worker.sh

  worker2:
    image: spark-worker:2.3.3

    volumes:
      - "${PWD}/data:/spark/data"

    user: root

    # command to start spark server
    command: /spark/start-spark-worker.sh

  pyspnb:
    image: spark-pyspnb:2.3.3

    ports:
      - "8888:8888"  # jupyter notebook server
      - "4040:4040"  # spark job web ui

    volumes:
      - "${CODE_DIR:-/tmp}:/opt/project"

    user: root

    # command jupyter notebook server
    command: /spark/start-pyspnb.sh

#
#    tty: true
#    stdin_open: true