version: '3'


services:

# Spark containers
  master:
    image: spark-master:2.3.3
    
    ports:
      - "7077:7077"
      - "6066:6066"
      - "8080:8080"

    volumes:
      - "${PWD}/data:/spark/data"

    user: root

    # command to start spark server
    command: /spark/start-spark-master.sh

  worker:
    image: spark-worker:2.3.3

#    ports:
#      - "7077:7077"
#      - "6066:6066"
#      - "8080:8080"

    volumes:
      - "${PWD}/data:/spark/data"


    user: root

    # command to start spark server
    command: /spark/start-spark-worker.sh

  pyspnb:
    image: spark-pyspnb:2.3.3

    ports:
      - "8888:8888"

    volumes:
      - "/Users/jim/Desktop/datascience_sample:/opt/project"

    user: root

    # command jupyter notebook server
    command: /spark/start-pyspnb.sh

#
#    tty: true
#    stdin_open: true