version: '3'


services:

# Spark containers
  spark-master:
    image: "spark-master:${APACHE_SPARK_VERSION}"

    hostname: spark-master
    
    ports:
      - "8080:8080"  # Spark master web UI

    volumes:
      - "${DATA_DIR:-/tmp}:/spark/data"

    user: root

    # command to start spark server
    command: /spark/start-spark-master.sh

  spark-worker1:
    image: "spark-worker:${APACHE_SPARK_VERSION}"

    hostname: spark-worker1

    ports:
      - "18081:18081"

    volumes:
      - "${DATA_DIR:-/tmp}:/spark/data"

    user: root

    # command to start spark server
    command: /spark/start-spark-worker.sh spark://spark-master:7077  --cores 4 --memory 4g --webui-port 18081

  spark-worker2:
    image: "spark-worker:${APACHE_SPARK_VERSION}"

    hostname: spark-worker2

    ports:
      - "28081:28081"

    volumes:
      - "${DATA_DIR:-/tmp}:/spark/data"

    user: root

    # command to start spark server
    command: /spark/start-spark-worker.sh spark://spark-master:7077 --cores 4 --memory 4g  --webui-port 28081

  pyspnb-client:
    image: "spark-pyspnb:${APACHE_SPARK_VERSION}"

    hostname: pyspnb-client

    ports:
      - "8888:8888"  # jupyter notebook server
      - "4040-4041:4040-4041"  # spark job web ui

    volumes:
      - "${CODE_DIR:-/tmp}:/opt/project"
      - "${DATA_DIR:-/tmp}:/spark/data"

    user: root

    # command jupyter notebook server
    command: /spark/start-pyspnb.sh
