services:
  pyspnb-client:
    command: /spark/start-pyspnb.sh
    hostname: pyspnb-client
    image: spark-pyspnb:2.4.1
    ports:
    - 8888:8888/tcp
    - 4040:4040/tcp
    - 4041:4041/tcp
    user: root
    volumes:
    - /Users/jim/Desktop/docker_sandbox/spark-docker-cluster/project:/opt/project:rw
    - /Users/jim/Desktop/docker_sandbox/spark-docker-cluster/data:/spark/data:rw
  spark-master:
    command: /spark/start-spark-master.sh
    hostname: spark-master
    image: spark-master:2.4.1
    ports:
    - 8080:8080/tcp
    user: root
    volumes:
    - /Users/jim/Desktop/docker_sandbox/spark-docker-cluster/data:/spark/data:rw
  spark-worker1:
    command: /spark/start-spark-worker.sh  --cores 4 --memory 4g --webui-port 18081
    hostname: spark-worker1
    image: spark-worker:2.4.1
    ports:
    - 18081:18081/tcp
    user: root
    volumes:
    - /Users/jim/Desktop/docker_sandbox/spark-docker-cluster/data:/spark/data:rw
  spark-worker2:
    command: /spark/start-spark-worker.sh  --cores 4 --memory 4g  --webui-port 28081
    hostname: spark-worker2
    image: spark-worker:2.4.1
    ports:
    - 28081:28081/tcp
    user: root
    volumes:
    - /Users/jim/Desktop/docker_sandbox/spark-docker-cluster/data:/spark/data:rw
version: '3.0'

